"""add assessments, assessment_questions, assessment_assignments, student_submissions, submission_answers

Revision ID: 05ec4ed1c933
Revises: 9181acbbb9bc
Create Date: 2026-09-29 16:33:31.960999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05ec4ed1c933'
down_revision: Union[str, None] = '9181acbbb9bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('lesson_plan_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('assessment_type', sa.Enum('FORMATIVE', 'SUMMATIVE', 'QUIZ', name='assessment_type'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_plan_id'], ['lesson_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_lesson_plan_id'), 'assessments', ['lesson_plan_id'], unique=False)
    op.create_table('assessment_assignments',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_assignments_assessment_id'), 'assessment_assignments', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_assignments_class_id'), 'assessment_assignments', ['class_id'], unique=False)
    op.create_table('assessment_questions',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.Enum('MCQ', 'SHORT_ANSWER', 'ESSAY', name='question_type'), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer_text', sa.Text(), nullable=True),
    sa.Column('max_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('order_index', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_questions_assessment_id'), 'assessment_questions', ['assessment_id'], unique=False)
    op.create_table('student_submissions',
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'ANALYZED', name='submission_status'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assessment_assignments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'student_id', name='uq_submission_assignment_student')
    )
    op.create_index(op.f('ix_student_submissions_assignment_id'), 'student_submissions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_student_submissions_student_id'), 'student_submissions', ['student_id'], unique=False)
    op.create_table('submission_answers',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_questions.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['student_submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'question_id', name='uq_answer_submission_question')
    )
    op.create_index(op.f('ix_submission_answers_question_id'), 'submission_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_submission_answers_submission_id'), 'submission_answers', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_answers_submission_id'), table_name='submission_answers')
    op.drop_index(op.f('ix_submission_answers_question_id'), table_name='submission_answers')
    op.drop_table('submission_answers')
    op.drop_index(op.f('ix_student_submissions_student_id'), table_name='student_submissions')
    op.drop_index(op.f('ix_student_submissions_assignment_id'), table_name='student_submissions')
    op.drop_table('student_submissions')
    op.drop_index(op.f('ix_assessment_questions_assessment_id'), table_name='assessment_questions')
    op.drop_table('assessment_questions')
    op.drop_index(op.f('ix_assessment_assignments_class_id'), table_name='assessment_assignments')
    op.drop_index(op.f('ix_assessment_assignments_assessment_id'), table_name='assessment_assignments')
    op.drop_table('assessment_assignments')
    op.drop_index(op.f('ix_assessments_lesson_plan_id'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
