"""add class_analytics_snapshots

Revision ID: 06788007aea6
Revises: 921c42051a45
Create Date: 2026-09-30 21:41:25.791511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06788007aea6'
down_revision: Union[str, None] = '921c42051a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_analytics_snapshots',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('average_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('submission_count', sa.Integer(), nullable=False),
    sa.Column('score_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('common_misconceptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_analytics_snapshots_class_id'), 'class_analytics_snapshots', ['class_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_class_analytics_snapshots_class_id'), table_name='class_analytics_snapshots')
    op.drop_table('class_analytics_snapshots')
    # ### end Alembic commands ###
