"""add ai_request_logs table

Revision ID: 501b6b547f89
Revises: 7b5c5ecc13c2
Create Date: 2026-09-27 18:30:58.048076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '501b6b547f89'
down_revision: Union[str, None] = '7b5c5ecc13c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
