"""create lesson_plans and lesson contents

Revision ID: 68b4c56cf587
Revises: e8195070ce4a
Create Date: 2026-09-21 15:03:39.490779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68b4c56cf587'
down_revision: Union[str, None] = 'e8195070ce4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_plans',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('student_count', sa.SmallInteger(), nullable=False),
    sa.Column('duration_minutes', sa.SmallInteger(), nullable=False),
    sa.Column('curriculum', sa.String(length=255), nullable=True),
    sa.Column('ability_level', sa.String(length=50), nullable=False),
    sa.Column('learning_context', sa.String(length=100), nullable=True),
    sa.Column('additional_instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATED', 'PUBLISHED', name='lesson_status'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='ck_lesson_plans_duration_positive'),
    sa.CheckConstraint('student_count > 0', name='ck_lesson_plans_student_count_positive'),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_plans_class_id'), 'lesson_plans', ['class_id'], unique=False)
    op.create_index(op.f('ix_lesson_plans_school_id'), 'lesson_plans', ['school_id'], unique=False)
    op.create_index(op.f('ix_lesson_plans_teacher_id'), 'lesson_plans', ['teacher_id'], unique=False)
    op.create_table('lesson_contents',
    sa.Column('lesson_plan_id', sa.UUID(), nullable=False),
    sa.Column('learning_objective', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('teaching_activity', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('differentiated_activities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assessment_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('marking_rubric', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('homework', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('revision_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('ai_provider_used', sa.String(length=50), nullable=False),
    sa.Column('ai_model_used', sa.String(length=100), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_plan_id'], ['lesson_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_plan_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson_contents')
    op.drop_index(op.f('ix_lesson_plans_teacher_id'), table_name='lesson_plans')
    op.drop_index(op.f('ix_lesson_plans_school_id'), table_name='lesson_plans')
    op.drop_index(op.f('ix_lesson_plans_class_id'), table_name='lesson_plans')
    op.drop_table('lesson_plans')
    # ### end Alembic commands ###
