"""make lesson_plans.class_id nullable

Revision ID: 6c51ca975058
Revises: 501b6b547f89
Create Date: 2026-09-27 18:55:32.461843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c51ca975058'
down_revision: Union[str, None] = '501b6b547f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lesson_plans', 'class_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_lesson_plans_class_id', table_name='lesson_plans')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_lesson_plans_class_id', 'lesson_plans', ['class_id'], unique=False)
    op.alter_column('lesson_plans', 'class_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
