"""drop redundant unique constraints on id columns

Revision ID: 7a49be30c785
Revises: 451c40d5ee2a
Create Date: 2026-09-17 11:14:33.048220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a49be30c785'
down_revision: Union[str, None] = '451c40d5ee2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('refresh_tokens_id_key', 'refresh_tokens', type_='unique')
    op.drop_constraint('schools_id_key', 'schools', type_='unique')
    op.drop_constraint('student_profiles_id_key', 'student_profiles', type_='unique')
    op.drop_constraint('teacher_profiles_id_key', 'teacher_profiles', type_='unique')
    op.drop_constraint('users_id_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_id_key', 'users', ['id'])
    op.create_unique_constraint('teacher_profiles_id_key', 'teacher_profiles', ['id'])
    op.create_unique_constraint('student_profiles_id_key', 'student_profiles', ['id'])
    op.create_unique_constraint('schools_id_key', 'schools', ['id'])
    op.create_unique_constraint('refresh_tokens_id_key', 'refresh_tokens', ['id'])
    # ### end Alembic commands ###
