"""add ai_request_logs, assessments, submissions, submission_analyses, score_override_audits, school ai/policy columns

Revision ID: 7b5c5ecc13c2
Revises: e83ea4016b82
Create Date: 2026-09-27 18:02:49.759074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b5c5ecc13c2'
down_revision: Union[str, None] = 'e83ea4016b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
