"""add grade_release_policy, submission review fields, score_override_audits

Revision ID: 921c42051a45
Revises: ac4862220e03
Create Date: 2026-09-30 15:59:42.258184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921c42051a45'
down_revision: Union[str, None] = 'ac4862220e03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_override_audits',
    sa.Column('submission_answer_id', sa.UUID(), nullable=False),
    sa.Column('previous_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('new_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('overridden_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['overridden_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_answer_id'], ['submission_answers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    grade_release_policy_enum = sa.Enum(
        'AUTO_RELEASE', 'REQUIRES_TEACHER_REVIEW', name='grade_release_policy'
    )
    grade_release_policy_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column('schools', 'grade_release_policy',
               existing_type=sa.VARCHAR(length=30),
               type_=grade_release_policy_enum,
               existing_nullable=False,
               postgresql_using='grade_release_policy::grade_release_policy')
    op.add_column('student_submissions', sa.Column('reviewed_by', sa.UUID(), nullable=True))
    op.add_column('student_submissions', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key('fk_student_submissions_reviewed_by_users', 'student_submissions', 'users', ['reviewed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_student_submissions_reviewed_by_users', 'student_submissions', type_='foreignkey')
    op.drop_column('student_submissions', 'reviewed_at')
    op.drop_column('student_submissions', 'reviewed_by')
    op.alter_column('schools', 'grade_release_policy',
               existing_type=sa.Enum('AUTO_RELEASE', 'REQUIRES_TEACHER_REVIEW', name='grade_release_policy'),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    sa.Enum(name='grade_release_policy').drop(op.get_bind(), checkfirst=True)
    op.drop_table('score_override_audits')
    # ### end Alembic commands ###