"""make class_id, ai_provider_used, ai_model_used nullable

Revision ID: a76ee0ac044b
Revises: 6c51ca975058
Create Date: 2026-09-27 19:43:29.136878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a76ee0ac044b'
down_revision: Union[str, None] = '6c51ca975058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lesson_contents', 'ai_provider_used',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('lesson_contents', 'ai_model_used',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lesson_contents', 'ai_model_used',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('lesson_contents', 'ai_provider_used',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
