"""add school_ai_settings

Revision ID: ac4862220e03
Revises: 39d0df4d756e
Create Date: 2026-09-30 14:02:37.883015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac4862220e03'
down_revision: Union[str, None] = '39d0df4d756e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_ai_settings',
    sa.Column('school_id', sa.UUID(), nullable=False),
    sa.Column('preferred_provider', sa.String(length=50), nullable=False),
    sa.Column('preferred_model', sa.String(length=100), nullable=True),
    sa.Column('monthly_token_budget', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('school_ai_settings')
    # ### end Alembic commands ###
